# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  deploy:
    docker:
      - image: cimg/base:2021.02
    steps:
      - checkout
      - run:
          name: Deploy Files Over SSH
          command: |
             scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v index.html "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
             scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -r css "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
             scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -r files "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
             scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -r imgs "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
             scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -r js "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"

workflows:

  version: 2
  
  ssh-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: circleci-project-setup # FIXME replace by master once tested